name: ufu_call
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+7
  #camera_windows: ^0.2.1+8  
  cupertino_icons: ^1.0.5  
  flutter_speed_dial: ^7.0.0
  path: ^1.8.2
  path_provider: ^2.0.14
  permission_handler: ^11.1.0
  dio: ^5.4.0  
  flutter_modular: ^6.3.2
  device_info_plus: ^9.1.1
  bordered_text: ^2.0.0
  badges: ^3.0.3
  icon_badge: ^1.0.0
  rx_notifier: ^2.2.1
  brasil_fields: ^1.11.0
  dotted_border: ^2.0.0+3
  source_gen: ^1.2.7
  hive: ^2.2.3
  hive_generator: ^2.0.0
  hive_flutter: ^1.1.0
  http_parser: ^4.0.2
  intl: ^0.18.0
  image: ^4.0.15
  tflite_flutter: ^0.10.3
  google_mlkit_face_detection: ^0.9.0
  google_mlkit_commons: ^0.6.1
  ml_linalg: ^13.11.30
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.2.2
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  flutter_form_builder: ^9.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3


# Execute o comando para altera o icone: dart run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icon/ufuIcon.png" 
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/ufuIcon.png
    - assets/images/background.png
    - assets/images/logo_ufu.png
    - assets/images/semFoto.png


scripts:
  mobx: dart run build_runner watch --delete-conflicting-outputs
  clean: dart run build_runner clean
  build: dart run build_runner build --delete-conflicting-outputs